# Generated by Django 4.1.4 on 2023-08-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_payslip_earning_in_words_payslip_effective_work_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='earning_in_words',
        ),
    ]
