# Generated by Django 4.1.4 on 2023-08-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_remove_payslip_earning_in_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='loss_pay_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_pay_days',
            field=models.FloatField(default=0.0),
        ),
    ]
