# Generated by Django 4.1.4 on 2023-08-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_alter_payslip_loss_pay_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='generated_payslip',
            new_name='dispatched_payslip',
        ),
    ]
