# Generated by Django 4.1.4 on 2023-08-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_rename_generated_payslip_payslip_dispatched_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='addition_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='addition_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='deduction_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='deduction_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
